
export const serviceTypes = [{
        title: 'Exclusively on ',
        slug: 'exclusives'
    }, {
        title: 'Trending on ',
        slug: 'trend'
    }, {
        title: 'Recently Released on ',
        slug: 'recently-released'
    }, {
        title: 'Popular now on ',
        slug: 'platform-popular'
    }, {
        title: '',
        slug: 'watchlist'
    }
];

export const services = [{
    name: 'Disney Plus',
    slug: 'disney-plus'
}, {
    name: 'Netflix',
    slug: 'netflix'
}, {
    name: 'Hulu',
    slug: 'hulu'
}, {
    name: 'Amazon Prime Video',
    slug: 'amazon-prime-video'
}, {
    name: 'Apple TV',
    slug: 'apple-tv-plus'
},];


export const getPopularPlexGenresFromService = (plexToken, service) => {
    return fetch(`https://discover.provider.plex.tv/library/platforms/${service}/popular-genres?X-Plex-Token=${plexToken}&X-Plex-Provider-Version=6.4`, {
        method: "GET",
        headers: {
            "accept": "application/json, text/plain, */*",
        },
    }).then(response => response.json())
    .then(data => {
        return data
    });
}

export const getPlexMostWatchlisted = (plexToken) => {
    return fetch(`https://discover.provider.plex.tv/hubs/sections/home/top_watchlisted?X-Plex-Token=${plexToken}&X-Plex-Language=en`, {
        method: "GET",
        headers: {
            "accept": "application/json, text/plain, */*",
        },
    }).then(response => response.json())
    .then(data => {
        return data
    });
}

export const getPlexServiceGenres = (plexToken, service, genre) => {
    return fetch(`https://discover.provider.plex.tv/library/platforms/${service}/genre-popular-${genre}?X-Plex-Token=${plexToken}`, {
        method: "GET",
        headers: {
            "accept": "application/json, text/plain, */*",
        },
    }).then(response => response.json())
    .then(data => {
        return data
    })
}

export const getPlexServiceRankings = (plexToken, service, type) => {
    return fetch(`https://discover.provider.plex.tv/library/platforms/${service}/${type}?X-Plex-Token=${plexToken}`, {
        method: "GET",
        headers: {
            "accept": "application/json, text/plain, */*",
        },
    }).then(response => response.json())
    .then(data => {
        return data
    })
}


// Awards:
// https://discover.provider.plex.tv/library/awards/academy-awards:1929-2023?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.118.0&X-Plex-Client-Identifier=n6orbtyt3sssd5m6c9o4qjib&X-Plex-Platform=Chrome&X-Plex-Platform-Version=119.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1609x999%2C3440x1440&X-Plex-Token=zv7Sx92aZ2KnLYze6Z8W&X-Plex-Provider-Version=6.4&X-Plex-Text-Format=plain&X-Plex-Language=en


// based on genre
// https://discover.provider.plex.tv/library/categories/animation?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.118.0&X-Plex-Client-Identifier=n6orbtyt3sssd5m6c9o4qjib&X-Plex-Platform=Chrome&X-Plex-Platform-Version=119.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1609x999%2C3440x1440&X-Plex-Token=zv7Sx92aZ2KnLYze6Z8W&X-Plex-Provider-Version=6.4&X-Plex-Text-Format=plain&X-Plex-Language=en

// More potential URLs to look through:
// https://vod.provider.plex.tv/hubs/sections/movies?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/recommended?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=12&X-Plex-Container-Size=48&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/plex-picks-of-the-week?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/binge-worthy-shows?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/newRentals?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/popularRentals?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/library/sections/categories/all?includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/library/sections/categories/all?includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/library/sections/channels/all?includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/library/sections/channels/all?includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/recommended?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=12&X-Plex-Container-Size=48&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/plex-picks-of-the-week?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/binge-worthy-shows?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/trending?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/cheap-thrills?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/expiring?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/true-crime?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/recentlyAdded?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/anime?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/based-on-a-true-story?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/movies/crime-time?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store?count=12&includeLibraryPlaylists=1&includeStations=1&includeRecentChannels=1&includeMeta=1&includeExternalMetadata=1&excludeFields=summary&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/newRentals?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/popularRentals?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/horror_rent?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/drama_rent?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/comedy_rent?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/romance_rent?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/adventure_rent?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/action_rent?contentDirectoryID=movies&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=24&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/myRentals?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/newRentals?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=85&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/popularRentals?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=35&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/horror_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=75&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/drama_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=75&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/comedy_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=73&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/romance_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=74&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/adventure_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=75&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/action_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=75&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/family_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/war_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/mystery_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/descriptiveAudioRentals?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/sci-fi_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/western_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en
// https://vod.provider.plex.tv/hubs/sections/store/fantasy_rent?contentDirectoryID=movies&X-Plex-Product=Plex%20Web&X-Plex-Version=4.130.0&X-Plex-Client-Identifier=0xrdp5hv33pjyqz8ok1xp1ic&X-Plex-Platform=Chrome&X-Plex-Platform-Version=124.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Screen-Resolution=1659x873%2C1728x1117&X-Plex-Container-Start=0&X-Plex-Container-Size=0&X-Plex-Token=8vhG8Wt9eeKr-fwgZc5j&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=widevine&X-Plex-Language=en